// src/components/PodcastsTags.tsx
import { cn } from "@/lib/utils";
import { PodcastsThemes } from "@/types/resources";
import { useStore } from "@nanostores/react";
import { selectedPodcast } from "./nanostore";
import { Button } from "./ui/button";

export default function ReactPodcastsTags() {
  const $selectedPodcast = useStore(selectedPodcast);
  return (
    <div
      className="flex gap-2 overflow-x-auto scroll-smooth px-4 md:px-8 py-4"
      style={{
        scrollbarWidth: "none",
      }}
    >
      {Object.values(PodcastsThemes).map((theme) => (
        <Button
          key={theme}
          value={theme}
          className={cn(
            "rounded-full transition-none",
            $selectedPodcast !== theme &&
              "bg-secondary/80 text-secondary-foreground hover:text-secondary"
          )}
          onClick={() => selectedPodcast.set(theme)}
        >
          {theme}
        </Button>
      ))}
    </div>
  );
}

// src/components/PodcastsTags.vue
<template>
    <div
        class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 auto-rows-fr xl:flex gap-4 mt-5 py-5 text-primary px-4 md:px-8">
        <button :class="[
            'px-4 py-1 rounded-2xl transition duration-300 text-sm font-semibold shadow-md',
            buttonClass(tag)
        ]" v-for="(tag, key) in PodcastsThemes" :key="key" @click="selectedPodcast.set(tag)">
            {{ tag }}
        </button>
    </div>
</template>

<script setup lang="ts">
import { PodcastsThemes } from '@/types/resources';
import { useStore } from '@nanostores/vue';
import { computed, onMounted, ref } from 'vue';
import { selectedPodcast } from './nanostore';

const $selectedPodcast = useStore(selectedPodcast);

const isMounted = ref(false);

onMounted(() => {
    isMounted.value = true;
});

const buttonClass = computed(() => (tag: string) => {
    if (!isMounted.value) {
        return 'bg-white';
    }
    return $selectedPodcast.value === tag ? 'bg-primary text-white' : 'bg-white';
});
</script>
